# Site settings
title: "vtext"
bye_message: "Thx!"
baseurl: "/"
url: "https://vtext.github.io"
disqus: vtext

# Header settings
nick: "vtext"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "vtext"
blog:
    server: "wordpress.com"
    nick: "vtext"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
